// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// matchrecs
DataFrame matchrecs(DataFrame adf, DataFrame bdf);
RcppExport SEXP _filematch_matchrecs(SEXP adfSEXP, SEXP bdfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type adf(adfSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type bdf(bdfSEXP);
    rcpp_result_gen = Rcpp::wrap(matchrecs(adf, bdf));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_filematch_matchrecs", (DL_FUNC) &_filematch_matchrecs, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_filematch(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
