# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Good approach
#'
#' Fast matching of records
#' @param adf a dataframe
#' @param bdf a dataframe
#' @return ab dataframe
#' @export
matchrecs <- function(adf, bdf) {
    .Call(`_filematch_matchrecs`, adf, bdf)
}

